version: '3'

services:
  franchises-crud:
    build: ./
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL:
      DB_USERNAME: admin
      DB_PASSWORD: password
    restart: always