version: '3'

services:
  franchises-crud:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://localhost:3306/test
      DB_USERNAME: admin
      DB_PASSWORD: password
    restart: always